# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RUserChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginname', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='channel_id',
            new_name='y_channel_id',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='channel_id',
            new_name='y_video_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_id',
        ),
        migrations.AddField(
            model_name='video',
            name='channel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='frontend.Channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ruserchannel',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Channel'),
        ),
        migrations.AddField(
            model_name='ruserchannel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.User'),
        ),
    ]
