# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20161115_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='y_channel_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='y_video_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
