# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20161115_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='user_video',
            new_name='users',
        ),
    ]
