# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20161119_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='playlist_uploads_id',
            field=models.CharField(default='bu', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='thumbnails',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='title',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnails',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='ruservideo',
            name='watched_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
