# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-15 17:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0008_auto_20161124_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='RUserChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_vid', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('last_vid_pub_date', models.DateTimeField(blank=True, null=True)),
                ('last_vid_y_vid_id', models.CharField(blank=True, max_length=200, null=True)),
                ('avg_freq_per_day', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='channel',
            name='imported_date',
        ),
        migrations.AddField(
            model_name='channel',
            name='username',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='ref_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ruserchannel',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Channel'),
        ),
        migrations.AddField(
            model_name='ruserchannel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='users2',
            field=models.ManyToManyField(related_name='users2', through='frontend.RUserChannel', to=settings.AUTH_USER_MODEL),
        ),
    ]
