# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-15 17:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0010_remove_channel_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='users2',
        ),
        migrations.AddField(
            model_name='channel',
            name='users',
            field=models.ManyToManyField(through='frontend.RUserChannel', to=settings.AUTH_USER_MODEL),
        ),
    ]
