"""
Django settings for yqueuer project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import sys
import re

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def readSecrets():
    config = SECRETS_EXPECTED_CONFIG.copy()
    for key in config:
        if os.environ.get(key):
            config[key] = os.environ.get(key)
            print >>sys.stderr, 'SECRETS CONFIG: adding:', key, os.environ.get(key)
        else :
            print >>sys.stderr, 'SECRETS CONFIG: Ignoring:', key

    # f = open(SECRETS_PATH, 'r')
    # for line in f:
    #     matches = re.search('^(\w*)=(.*)$', line)
    #     if matches:
    #         key = matches.group(1)
    #         if SECRETS_EXPECTED_CONFIG.has_key(key):
    #             value = matches.group(2)
    #             config[key] = value
    #         else :
    #             print >>sys.stderr, 'SECRETS CONFIG: Ignoring:', key

    return config

# Read secrets from file
SECRETS_PATH = BASE_DIR + '/../config/dev_secrets.properties'
SECRETS_EXPECTED_CONFIG = {
    'SECRET_KEY': '',
    'DB_USER': '',
    'DB_PASS': '',
    'ALLOWED_HOSTS': '',
    'YOUTUBE_API_KEY': '',
}

SECRETS = readSecrets()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = SECRETS['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [SECRETS['ALLOWED_HOSTS']]

# Application definition

INSTALLED_APPS = [
    'frontend.apps.FrontendConfig',
# Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'yqueuer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yqueuer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'yqueuer',
        'USER': SECRETS['DB_USER'],
        'PASSWORD': SECRETS['DB_PASS'],
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, "static/")

LOGIN_URL = '/login/'